resources:
- repo: self

variables:
  major: 1
  minor: 0

name: $(major).$(minor).$(rev:r)

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.2.100'
  inputs:
    version: 2.2.100

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    arguments: '-c Release'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\*test*.dll
     !**\*TestAdapter.dll
     !**\obj\**
     !**\*Integration*.dll
    runOnlyImpactedTests: false
    codeCoverageEnabled: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory) --no-build'
    zipAfterPublish: false

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: |
     maintenance/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: server-drop'
  inputs:
    ArtifactName: 'server-drop'
